### ISSUE TITLE
privacy doc

### ISSUE THREAD

**Issue by adipasquale** [shinework/photoshot#1]
add a page that describes the privacy concerns 

- where is the data stored
- how long is it going to be stored for
- who can it be transmitted to

the [privacy policy of Replicate](https://replicate.com/privacy) is slightly concerning :|
> We may disclose your information also:    
> to our subsidiaries and affiliates;
>  to contractors, service providers, and other third parties we use to support our business;

**Comment by kunimei** [comment]
very good

**Comment by shinework** [comment]
FAQ and Terms page have been added

**Comment by adipasquale** [comment]
thanks 🙇
