### ISSUE TITLE
Can this be self-hosted and trained locally?

### ISSUE THREAD

**Issue by pluja** [shinework/photoshot#10]
I don't see it clear if this can be run locally and trained locally. Is it possible?

**Comment by clemsau** [comment]
The React app can be run locally, but you can read in the `README.md` file that the platform [Replicate](https://replicate.com/) is used to train and run the model (stable diffusion). 
It would be pretty expensive and way more complex to do the AI parts on your own machine.

**Comment by dalaohuniu** [comment]
ok i know you are good
