### ISSUE TITLE
Can you provide a more detailed text to run it?

### ISSUE THREAD

**Issue by oscarcalvo** [shinework/photoshot#13]
If I clone the repo and run it according the readme, I get a "TypeError [ERR_INVALID_URL]: Invalid URL". I see env.example is empty so maybe a good start is to fill it with some dumb data or explain it. Also it speaks about "DATABASE_URL" and it would be great the type of bbdd needed and if it has a script to install it when you run the app or you need make it yourself etc etc

Thanks

**Comment by gud99008** [comment]
cool

**Comment by tarikmehinagic** [comment]
> If I clone the repo and run it according the readme, I get a "TypeError [ERR_INVALID_URL]: Invalid URL". I see env.example is empty so maybe a good start is to fill it with some dumb data or explain it. Also it speaks about "DATABASE_URL" and it would be great the type of bbdd needed and if it has a script to install it when you run the app or you need make it yourself etc etc
> 
> Thanks

AFAIK `DATABASE_URL` is generated by prisma and here's an example: `DATABASE_URL="postgresql://user:pw@localhost:5432/db_name?schema=public"`

**Comment by MontaEllis** [comment]
Same error. Could you please explain how to fill the env file?

**Comment by shinework** [comment]
Hello, I've just added more details about .env and docker in the readme
