### ISSUE TITLE
Failed yarn install some modules on M1 Arm architecture

### ISSUE THREAD

**Issue by selcukkubur** [shinework/photoshot#14]
Hi there, firstly thanks for your work but I'm getting installation some dependency’s on m1 arm

`info @next/swc-android-arm-eabi@13.0.6: The platform "darwin" is incompatible with this module.
info "@next/swc-android-arm-eabi@13.0.6" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-android-arm-eabi@13.0.6: The CPU architecture "arm64" is incompatible with this module.
info @next/swc-android-arm64@13.0.6: The platform "darwin" is incompatible with this module.
info "@next/swc-android-arm64@13.0.6" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-linux-arm64-gnu@13.0.6: The platform "darwin" is incompatible with this module.
info "@next/swc-linux-arm64-gnu@13.0.6" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-linux-x64-gnu@13.0.6: The platform "darwin" is incompatible with this module.
info "@next/swc-linux-x64-gnu@13.0.6" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-linux-x64-gnu@13.0.6: The CPU architecture "arm64" is incompatible with this module.
info @next/swc-linux-x64-musl@13.0.6: The platform "darwin" is incompatible with this module.
info "@next/swc-linux-x64-musl@13.0.6" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-linux-x64-musl@13.0.6: The CPU architecture "arm64" is incompatible with this module.
info @next/swc-linux-arm-gnueabihf@13.0.6: The platform "darwin" is incompatible with this module.
info "@next/swc-linux-arm-gnueabihf@13.0.6" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-linux-arm-gnueabihf@13.0.6: The CPU architecture "arm64" is incompatible with this module.
info @next/swc-freebsd-x64@13.0.6: The platform "darwin" is incompatible with this module.
info "@next/swc-freebsd-x64@13.0.6" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-freebsd-x64@13.0.6: The CPU architecture "arm64" is incompatible with this module.
info @next/swc-linux-arm64-musl@13.0.6: The platform "darwin" is incompatible with this module.
info "@next/swc-linux-arm64-musl@13.0.6" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-win32-arm64-msvc@13.0.6: The platform "darwin" is incompatible with this module.
info "@next/swc-win32-arm64-msvc@13.0.6" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-win32-ia32-msvc@13.0.6: The platform "darwin" is incompatible with this module.
info "@next/swc-win32-ia32-msvc@13.0.6" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-win32-ia32-msvc@13.0.6: The CPU architecture "arm64" is incompatible with this module.
info @next/swc-win32-x64-msvc@13.0.6: The platform "darwin" is incompatible with this module.
info "@next/swc-win32-x64-msvc@13.0.6" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-win32-x64-msvc@13.0.6: The CPU architecture "arm64" is incompatible with this module.
info @next/swc-darwin-x64@13.0.6: The CPU architecture "arm64" is incompatible with this module.
info "@next/swc-darwin-x64@13.0.6" is an optional dependency and failed compatibility check. Excluding it from installation.
error next-auth@4.18.6: The engine "node" is incompatible with this module. Expected version "^12.19.0 || ^14.15.0 || ^16.13.0 || ^18.12.0". Got "19.2.0"
error Found incompatible module.`

**Comment by shinework** [comment]
Hello @selcukkubur

> Expected version "^12.19.0 || ^14.15.0 || ^16.13.0 || ^18.12.0". Got "19.2.0" error Found incompatible module.

You need to use the LTS node version (18)
