### ISSUE TITLE
Can you deploy this app to hosting service?

### ISSUE THREAD

**Issue by startjourney9** [shinework/photoshot#15]

**Comment by tarikmehinagic** [comment]
You can deploy it easily with Vercel: https://vercel.com/guides/deploying-nextjs-with-vercel

**Comment by shinework** [comment]
Yes as @tarikmehinagic said, you can easily deploy this Next.js app on Vercel (for free)

**Comment by startjourney9** [comment]
@tarikmehinagic , @shinework , thanks for your comments. After deploying, can I add link to this repo?
