### ISSUE TITLE
Naming the (Studio) should be a unique

### ISSUE THREAD

**Issue by ahmadaIanazi** [shinework/photoshot#20]
The A.I. model that is generated by the studio, is sometimes gets confused I think with other users model who have similar (Studio Names) which is very very strange ? 

Is that possible ? 

and if it is possible would it be better to have the studio name have a global Unique ID to avoid any crossing with other studios.

**Comment by shinework** [comment]
Each model operates independently, but if the subject's name is not unique enough, there is a risk of confusing it with other concepts. To improve the model's results, it is crucial to choose a subject name that is distinct and unambiguous.

**Comment by ahmadaIanazi** [comment]
Thank you for the clarification.
