### ISSUE TITLE
Getting 'Greeting never received' error

### ISSUE THREAD

**Issue by quacrobat** [shinework/photoshot#25]
Hi, trying to test in github codespaces. 
I followed all the steps in the readme, but I never receive the email magic link when I try to signup/login.
I get:
```
https://next-auth.js.org/errors#signin_email_error Greeting never received {
  error: {
    message: 'Greeting never received',
    stack: 'Error: Greeting never received\n' +
      '    at SMTPConnection._formatError (/workspaces/photoshot-0/node_modules/nodemailer/lib/smtp-connection/index.js:790:19)\n' +
      '    at SMTPConnection._onError (/workspaces/photoshot-0/node_modules/nodemailer/lib/smtp-connection/index.js:776:20)\n' +
      '    at Timeout.<anonymous> (/workspaces/photoshot-0/node_modules/nodemailer/lib/smtp-connection/index.js:710:22)\n' +
      '    at listOnTimeout (node:internal/timers:559:17)\n' +
      '    at processTimers (node:internal/timers:502:7)',
    name: 'Error'
  },
  providerId: 'email',
  message: 'Greeting never received'
}
```

**Comment by shinework** [comment]
Hello @quacrobat, looks like you need to set up the right `EMAIL_SERVER` in the .env file

**Comment by quacrobat** [comment]
hmm, so it isn't this?
```
EMAIL_SERVER=smtp://localhost:1080
```

**Comment by quacrobat** [comment]
@shinework i am using mailgun, and have set the following format, 

`EMAIL_SERVER=smtp://username@xxxx.mailgun.org:password@smtp.mailgun.org:587`

based on mailgun's docs and this page: [https://next-auth.js.org/providers/email](url)

Still getting the same "Greeting never received" error. My mailgun account is fine, working for a different app. What am I doing wrong?

Note: all this is in github codespaces (not a problem for my other app using mailgun) and not on a production server.

Please help!

**Comment by quacrobat** [comment]
nevermind 🙊 i was using .env not .env.local...
