### ISSUE TITLE
Training keeps failing + unexpected model and someone else's photos on my replicate dashboard.

### ISSUE THREAD

**Issue by quacrobat** [shinework/photoshot#31]
Hi,
I am able to upload images and pay and start the training, but it always fails with this error:
`We are sorry but the creation of the model failed. Please contact us by email so we can fix it/refund you.`

Looking at the replicate.com dashboard>Recent predictions, for each attempt, I see a model with Failed status.
![image](https://user-images.githubusercontent.com/4062597/210062441-8491a2ee-6e02-43d6-8ebb-51c59a43e06d.png)

Clicking on the ID, shows an Input and Output page, with a link to a .zip file that is broken under Input, and "404 Client Error" in the Output. It links to an unexisting .zip file on my S3 bucket.

**Question 1: is this a zip file that failed to ever be created or that was deleted by Photoshot when the training failed?**

Would this be a permissions issue and if so, what would need to change? Photoshot seems to be able to upload and read the images, so why not the zip?

Clicking on the Version link (replicate/dreambooth:...) shows a page with what seems to be someone else's training. The instance_prompt says `"a photo of bfirsh"` and a link to `data.zip` downloads a folder with ben firshman's photos (replicate's founder). Another link to `output.zip` gets what looks like a 2GB trained model.

**Question 2: are these a normal part of the process?**

Thanks

**Comment by quacrobat** [comment]
Issue goes away when you add a credit card to the replicate account. I was mislead by replicate's message that first trials are free.

**Comment by shuangjie** [comment]
Hello, I also encountered the same problem. No zip file was generated. How did you finally solve it?
