### ISSUE TITLE
Can use alternative models?

### ISSUE THREAD

**Issue by quacrobat** [shinework/photoshot#32]
Hello, is it possible to use alternative stable diffusion or other pre-trained models hosted on Replicate?
If so, how?
Thanks

**Comment by shinework** [comment]
Hello @quacrobat! Yes you can train your model based on a ckpt file, see https://gist.github.com/anotherjesse/e59fbd0f36090c6c873f059bc33485d8

**Comment by quacrobat** [comment]
Thank you @shinework I figured that part out, but what do i need to change on photoshot to point to the new model?

**Comment by shinework** [comment]
You need to change this call https://github.com/shinework/photoshot/blob/main/src/pages/api/projects/%5Bid%5D/train.ts#L26

Something like:

```ts
const responseReplicate = await replicateClient.post(
    "/v1/trainings",
    {
      input: {
        instance_prompt: `…`,
        class_prompt: `…`,
        instance_data: `…`,
        ckpt_base:
          "https://storage.googleapis.com/replicant-misc/openjourney-v2.ckpt",
      },
      trainer_version:
        "e08aad944e0cf515d59da9fe0f0a32278be9395505b17c71d0e6ff5ec0b91a8c",
      model: `${process.env.REPLICATE_USERNAME}/${project.id}`,
    },
    {
      headers: {
        Authorization: `Token ${process.env.REPLICATE_API_TOKEN}`,
        "Content-Type": "application/json",
      },
    }
  );
```

**Comment by quacrobat** [comment]
brilliant! thanks
