### ISSUE TITLE
.env variables errors

### ISSUE THREAD

**Issue by yongloon** [shinework/photoshot#44]
Hi developer, what do I need to generate those variables to run the project successfully? Is it generated, or anyway to get it? Any sample?

REPLICATE_HD_VERSION_MODEL_ID
NEXT_PUBLIC_REPLICATE_INSTANCE_TOKEN
OPENAI_API_SEED_PROMPT

**Comment by yongloon** [comment]
and i get this error
![image](https://user-images.githubusercontent.com/12860854/222743345-a40693b4-d52f-4567-ae8c-34a77fd579af.png)

**Comment by terryds** [comment]
anyone figured this out?

**Comment by rossman22590** [comment]
nope :)
